# Generated by Django 3.2.3 on 2021-05-29 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exponats', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exponat',
            options={'ordering': ['title']},
        ),
    ]
